<?php

namespace Database\Seeders;

use App\Models\Property;
use App\Models\PropertyAmenity;
use App\Models\PropertyCategory;
use App\Models\PropertyType;
use App\Models\User;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $agent = User::query()->where('email', 'agent@shinestarmarketing.test')->first();
        $agency = User::query()->where('email', 'agency@shinestarmarketing.test')->first();

        if (! $agent || ! $agency) {
            $this->command?->warn('Skipping PropertySeeder: demo agent/agency accounts not found. Run DemoUserSeeder first.');

            return;
        }

        $apartment = PropertyCategory::query()->where('name', 'Apartment')->first();
        $villa = PropertyCategory::query()->where('name', 'Villa')->first();
        $office = PropertyCategory::query()->where('name', 'Office')->first();
        $rent = PropertyType::query()->where('name', 'Rent')->first();
        $sale = PropertyType::query()->where('name', 'Sale')->first();

        if (! $apartment || ! $villa || ! $office || ! $rent || ! $sale) {
            $this->command?->warn('Skipping PropertySeeder: run PropertyCategorySeeder and PropertyTypeSeeder first.');

            return;
        }

        $amenityIds = PropertyAmenity::query()->inRandomOrder()->limit(3)->pluck('id');

        $samples = [
            [
                'user_id' => $agent->id, 'category_id' => $apartment->id, 'type_id' => $rent->id,
                'title' => 'Modern 2-Bed Apartment in Downtown', 'city' => 'Austin', 'price' => 1800,
                'status' => 'approved', 'lat' => 30.2672, 'lng' => -97.7431, 'bedrooms' => 2, 'bathrooms' => 2, 'size' => 1100,
            ],
            [
                'user_id' => $agency->id, 'category_id' => $villa->id, 'type_id' => $sale->id,
                'title' => 'Luxury Villa with Private Pool', 'city' => 'Miami', 'price' => 1250000,
                'status' => 'approved', 'lat' => 25.7617, 'lng' => -80.1918, 'bedrooms' => 5, 'bathrooms' => 4, 'size' => 4200,
                'is_featured' => true,
            ],
            [
                'user_id' => $agent->id, 'category_id' => $office->id, 'type_id' => $rent->id,
                'title' => 'Open-Plan Office Space', 'city' => 'Seattle', 'price' => 3200,
                'status' => 'pending', 'lat' => 47.6062, 'lng' => -122.3321, 'bedrooms' => null, 'bathrooms' => 2, 'size' => 2500,
            ],
            [
                'user_id' => $agency->id, 'category_id' => $apartment->id, 'type_id' => $sale->id,
                'title' => 'Cozy Studio Near the Park', 'city' => 'Denver', 'price' => 210000,
                'status' => 'rejected', 'rejection_reason' => 'Photos are too low-resolution, please re-upload.',
                'lat' => 39.7392, 'lng' => -104.9903, 'bedrooms' => 1, 'bathrooms' => 1, 'size' => 650,
            ],
        ];

        foreach ($samples as $data) {
            $property = Property::query()->firstOrCreate(
                ['title' => $data['title']],
                array_merge(['description' => 'Sample listing generated by PropertySeeder for demo/testing purposes.'], $data),
            );

            $property->amenities()->syncWithoutDetaching($amenityIds);
        }
    }
}
